CREATE DATABASE IF NOT EXISTS warehouse;

USE warehouse;
CREATE TABLE IF NOT EXISTS client (
  client_id integer PRIMARY KEY SERIAL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone_number VARCHAR(15),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product (
  product_id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  sku VARCHAR(20) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  description TEXT,
  price FLOAT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- TRIGGER must be assigned to this table
);

CREATE TABLE IF NOT EXISTS bill (
  bill_id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL,
  total FLOAT,
  status status_enum NOT NULL DEFAULT 'open',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- TRIGGER must be assigned to this table
);

CREATE TABLE IF NOT EXISTS bill_product (
  bill_product_id SERIAL PRIMARY KEY,
  bill_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  price FLOAT NOT NULL,
  discount INTEGER NOT NULL DEFAULT 0,
  date_added TIMESTAMP ,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- TRIGGER must be assigned to this table
);


CREATE TRIGGER bill_product_modified_at_trigger
BEFORE UPDATE ON bill_product
FOR EACH ROW
EXECUTE FUNCTION update_modified_at() ;